### ISSUE TITLE
Getting Error response while trying to get started with docker run command

### ISSUE THREAD

**Issue by smunveruddin-mwb** [heapland/heapland#34]
Hi,

Am getting an error response while trying to get started with docker run command as shown below

$ docker run -p 9080:9080 -v gxdb:/var heapland/heapland:0.3.0
Unable to find image 'heapland/heapland:0.3.0' locally
docker: Error response from daemon: manifest for heapland/heapland:0.3.0 not found: manifest unknown: manifest unknown.
See 'docker run --help'

Could you please help me with the above issue?

Thanks
Shabeer

**Comment by amezng** [comment]
@smunveruddin-mwb can you try again? this is fixed.

**Comment by smunveruddin-mwb** [comment]
@amezng Thanks for fixing it, I can able to start it using the quick start docker run command.

But the thing am trying to do is add a S3 connection and few things that i have tested is as follows which can be improved i believe.

- "Test connection" button at the right bottom when we add a new S3 connection does not show any output when clicked like "Connection is successful or not"
- I guess maybe right now it takes up only static AWS key and secret; what if there are profiles involved and also session token involved, then it does not connect to .

Like i said the above are some of the things i noticed when trying to test a S3 connection. And I say this is impressive work what you guys have done here. Good Job !! I'd really like to test more features of it.


Thanks
Shabeer

**Comment by amezng** [comment]
Thanks @smunveruddin-mwb for pointing out the issues. We are currently tracking them #36 and #37 .

Really appreciate for your kind words. Hope this turns out to be one stop for all the data services.
